version: 0.2

env:
  variables:
    ENV: dev

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "📦 Installing application and test dependencies..."
      - pip install --upgrade pip
      - pip install -U -r back-end-python/gameactions/requirements.txt
      - pip install -U -r back-end-python/tests/requirements.txt

  build:
    commands:
      - echo "🔍 Running code analysis with pylint..."
      - pylint --fail-under=8 back-end-python/gameactions/app.py

      - echo "🧪 Running unit tests with coverage..."
      - |
        pytest back-end-python/tests/unit \
          --junit-xml=unittests.xml \
          --cov-report=xml \
          --cov=gameactions \
          --cov-branch

  post_build:
    commands:
      - echo "📦 Building application with SAM..."
      - sam build --use-container

      - echo "📦 Packaging application for environment $ENV..."
      - |
        sam package \
          --s3-bucket trivia-app-$ENV-bucket-teste \
          --output-template-file packaged.yaml

reports:
  UnitTests:
    files:
      - 'unittests.xml'
  NewCoverage:
    files:
      - 'coverage.xml'
    file-format: COBERTURAXML

artifacts:
  files:
    - packaged.yaml  # Este é o ficheiro que será usado na fase de deploy
