version: 0.2  # Versão do formato do ficheiro buildspec

env:
  variables:
    ENV: dev  # Pode ser 'dev', 'qa' ou 'prod'. Define o ambiente de destino do deploy

phases:
  install:
    commands:
      - echo "🔧 Instalando Python 3.9 manualmente..."
      - amazon-linux-extras enable python3.8
      - yum install -y python3.8 python3.8-pip
      - ln -sf /usr/bin/python3.8 /usr/bin/python3.9
      - ln -sf /usr/bin/pip3.8 /usr/bin/pip3.9
      - alternatives --install /usr/bin/python python /usr/bin/python3.9 1
      - alternatives --install /usr/bin/pip pip /usr/bin/pip3.9 1
      - python --version
      - pip --version

      - echo "📦 Instalando dependências da aplicação e dos testes..."
      - pip install --upgrade pip
      - pip install -U -r back-end-python/gameactions/requirements.txt
      - pip install -U -r back-end-python/tests/requirements.txt

  build:
    commands:
      - echo "🔍 Analisando código com pylint..."
      - pylint --fail-under=8 back-end-python/gameactions/app.py

      - echo "🧪 Executando testes unitários com cobertura..."
      - pytest back-end-python/tests/unit \
          --junit-xml=unittests.xml \
          --cov-report=xml \
          --cov=gameactions \
          --cov-branch

  post_build:
    commands:
      - echo "📦 Construindo aplicação com SAM..."
      - sam build --use-container

      - echo "🚀 Empacotando aplicação para o ambiente $ENV..."
      - sam package \
          --s3-bucket trivia-app-$ENV \
          --output-template-file packaged.yaml

      - echo "☁️ Fazendo deploy para o ambiente $ENV..."
      - sam deploy \
          --template-file packaged.yaml \
          --stack-name trivia-app-$ENV \
          --capabilities CAPABILITY_IAM \
          --region eu-west-1 \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset

reports:
  UnitTests:
    files:
      - 'unittests.xml'
  NewCoverage:
    files:
      - 'coverage.xml'
    file-format: COBERTURAXML

artifacts:
  files:
    - template.yaml
    - packaged.yaml
    - build/**/*
